config/routes.rb
NormanJaffe::Application.routes.draw do
  get "welcome/index"

  get "welcome/projects"

  get "welcome/philosophy"

  get "welcome/biography"

  get "welcome/contact"

  root to: 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def projects
  end

  def philosophy
  end

  def biography
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NormanJaffe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!== Create Navigation links and style nav bar ==>
	<div class="container">
		<ul class="nav nav-tabs">
			<li><%= link_to "Home", welcome_index_path %></li>
			<li><%= link_to "Philosophy", welcome_philosophy_path %></li>
			<li><%= link_to "Projects", welcome_projects_path %></li>
			<li><%= link_to "Biography", welcome_biography_path %></li>
			<li><%= link_to "Contact", welcome_contact_path %></li>
		</ul>
	</div>

<%= yield %>

</body>
</html>

app/views/welcome/biography.html.erb
<h1>Welcome#biography</h1>
<p>Find me in app/views/welcome/biography.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/philosophy.html.erb
<h1>Welcome#philosophy</h1>
<p>Find me in app/views/welcome/philosophy.html.erb</p>

app/views/welcome/projects.html.erb
<h1>Welcome#projects</h1>
<p>Find me in app/views/welcome/projects.html.erb</p>